Algoritmo "exercicio_38"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Contagem
// Autor(a)    : Daniel Solano
// Data atual  : 21/10/2024
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para x de 5 ate 10 faca
x <- x + 1
escreva(x)
fimpara

Fimalgoritmo