Algoritmo "atv2_exercicio2"
// Disciplina: UC3 ALGORITIMOS
// Professor: Mateus de Paula Pereira
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2024
Var
// Seção de Declarações das variáveis
nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Qual é o seu nome?")
leia(nome)

escreva("Olá " , nome,", é um prazer te conhecer!")



Fimalgoritmo