Algoritmo "exercicio_40"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Contagem 4.0
// Autor(a)    : Daniel Solano
// Data atual  : 21/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
n <- 0
escreva(n)
repita
n <- n + 3
escreva(n)
ate n = 18
escreval("")
escreval("ACABOOOU!!!!!!")
Fimalgoritmo