Algoritmo "exercicio_39"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Contagem 2.0
// Autor(a)    : Daniel Solano
// Data atual  : 21/10/2024
Var
// Seção de Declarações das variáveis 
x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
x <- 11
repita
x <- x - 1
escreva(x)
ate x <= 3

Fimalgoritmo