Algoritmo "atv7_exercicio3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : MATEUS DE PAULA
// Descrição   : NÚMEROS ÍMPARES
// Autor(a)    : DANIEL SOLANO
// Data atual  : 09/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(n)

para n de 1 ate n faca
se n mod 2 = 1 entao
escreval(n)
fimse
fimpara

Fimalgoritmo