Algoritmo "atv7_exercicio1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : MATEUS DE PAULA FERREIRA
// Descrição   : NÚMEROS DE 1 A 100
// Autor(a)    : DANIEL SOLANO
// Data atual  : 09/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 1 ate 100 faca
 escreval(n)
 fimpara
 
Fimalgoritmo